[2025-05-20T17:53:05.679+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.load_csv manual__2025-05-20T17:53:01.572788+00:00 [queued]>
[2025-05-20T17:53:05.719+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.load_csv manual__2025-05-20T17:53:01.572788+00:00 [queued]>
[2025-05-20T17:53:05.721+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-20T17:53:05.781+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_csv> on 2025-05-20 17:53:01.572788+00:00
[2025-05-20T17:53:05.798+0000] {standard_task_runner.py:57} INFO - Started process 520 to run task
[2025-05-20T17:53:05.812+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'load_csv', 'manual__2025-05-20T17:53:01.572788+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dag_flight_pipeline.py', '--cfg-path', '/tmp/tmp9gtt1h49']
[2025-05-20T17:53:05.828+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask load_csv
[2025-05-20T17:53:06.049+0000] {task_command.py:416} INFO - Running <TaskInstance: flight_price_pipeline.load_csv manual__2025-05-20T17:53:01.572788+00:00 [running]> on host afdaae69c771
[2025-05-20T17:53:06.385+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='load_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T17:53:01.572788+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T17:53:01.572788+00:00'
[2025-05-20T17:53:06.392+0000] {load.py:6} INFO - Starting CSV load task
[2025-05-20T17:53:07.509+0000] {load.py:12} INFO - Loaded 57000 rows from CSV
[2025-05-20T17:53:07.703+0000] {load.py:53} ERROR - Error loading CSV to MySQL: 1054 (42S22): Unknown column 'Base Fare (BDT)' in 'field list'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'Base Fare (BDT)' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/tasks/load.py", line 44, in load_csv_to_mysql
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 86, in wrapper
    result = method(cnx, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'Base Fare (BDT)' in 'field list'
[2025-05-20T17:53:07.722+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 633, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown column 'Base Fare (BDT)' in 'field list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tasks/load.py", line 44, in load_csv_to_mysql
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 330, in execute
    result = self._cnx.cmd_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 86, in wrapper
    result = method(cnx, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 641, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'Base Fare (BDT)' in 'field list'
[2025-05-20T17:53:07.744+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=flight_price_pipeline, task_id=load_csv, execution_date=20250520T175301, start_date=20250520T175305, end_date=20250520T175307
[2025-05-20T17:53:07.777+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task load_csv (1054 (42S22): Unknown column 'Base Fare (BDT)' in 'field list'; 520)
[2025-05-20T17:53:07.802+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T17:53:07.852+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
